#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=${REMOTE_DATABASE_URL:jdbc:mysql://localhost:3307/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
#spring.datasource.username=${REMOTE_DATABASE_USER:root}
#spring.datasource.password=${REMOTE_DATABASE_PASSWORD:root}
#server.port=${PORT:8080}
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.data.rest.base-path=/api
# Show or not log for each sql query
#spring.jpa.show-sql = true

# Hibernate ddl auto (create, create-drop, update)
#spring.jpa.hibernate.ddl-auto=update

# H2 in-memory DB for testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Server port
server.port=8080

# Logging SQL (optional)
spring.jpa.show-sql=true

